version: '3'
services:
  whatsinit-app:
    container_name: whatsinit-app-container
    build:
      context: .
      dockerfile: Dockerfile-dev
    image: whatsinit-app:1.0-dev
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.4
    volumes:
      - ./:/usr/src
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
